### ISSUE TITLE
Data link is Broken

### ISSUE THREAD

**Issue by jannisborn** [AI4SCR/conditional-monge#8]

**Comment by sankethvedula** [comment]
This link works: https://www.research-collection.ethz.ch/handle/20.500.11850/609681

You could consider swapping it -- I believe the dataset was obtained from Bunne et al.'s CellOT paper, correct?

**Comment by jannisborn** [comment]
Ah yes, perfect that's it! Thanks! You can see in the `scrna-sciplex3` folder the 9 drugs that were used in CellOT and also in our work :)
